<?php
// Automatically Generated by TestLink Installer - Thu, 27 Nov 14 11:25:27 +0800
define('DB_TYPE', 'mysql');
define('DB_USER', 'testlink');
define('DB_PASS', 'password');
define('DB_HOST', '192.168.60.191');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
